- hosts: localhost
  # vars:
  #   personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  
  tasks:
    - inclide: tasks/defaults.yml
    - include: tasks/conda.yml