- hosts: localhost

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  
  tasks:
    - include: tasks/apps.yml
    - include: tasks/conda.yml
    - include: tasks/nvim.yml
    - include: tasks/nvim-osx.yml