- hosts: localhost
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    m3: "{{ home }}/miniconda3/bin"

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  
  tasks:
    - include: tasks/apps.yml
    - include: tasks/conda.yml