- name: Download and Install NeoVim
  hosts: 
    - all
    - "*"
    - localhost
  gather_facts: false
  vars_files: vars.yml

  tasks:
    - name: Install NVM OSX
      block:
        - name: Extract NVM
          shell: brew install neovim
        - name: Install ripgrep
          shell: brew install ripgrep
        - name: Install fzf
          shell: brew install fzf
        - name: Install TreeSitter
          shell: brew install --HEAD tree-sitter
        - name: Install Packer
          git: 
            repo: https://github.com/wbthomason/packer.nvim
            dest: '{{ home }}/.local/share/nvim/site/pack/packer/opt/packer.nvim'
            depth: 1
        - name: Add init
          get_url:
            url: https://raw.githubusercontent.com/c-jamie/dev-toolchain/master/dotfiles/init.lua
            dest: '{{ home }}/.config/nvim/init.lua'
            mode: '0700'
