- name: Install Conda
  block:
    - name: Install System Packages 1 (git)
      become: true
      apt:
        name: ["git"]
      tags:
        - install
    - name: Productivity
      become: true
      apt:
        name: [ "tmux", "fzf", "ripgrep" ]
      tags:
        - install
    - name: C++
      become: true
      apt:
        name: [ "make", "gcc"]
      tags:
        - install
  tags:
   - app