- name: Install Conda
  block:
    - name: Download Miniconda
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/install-miniconda.sh
    - name: Create conda folder
      file:
        path: "{{ home }}/miniconda3"
        state: directory
        recurse: yes
    - name: Run the installer
      shell: /tmp/install-miniconda.sh -b -u -p "{{ home }}/miniconda3"
    - name: Remove the installer
      file:
        state: absent
        path: /tmp/install-miniconda.sh
    - name: Add miniconda bin to path
      become: True
      shell: echo 'export PATH={{ home }}/miniconda3/bin:$PATH' >> {{ home }}/.profile
    - name: conda - read permission for all
      become: True
      file:
        path: "{{ home }}/miniconda3"
        mode: +r
        recurse: yes
    - name: conda - execution permission for all
      become: True
      file:
        path: "{{home}}/miniconda3/bin"
        mode: +x
        recurse: yes
    - name: update conda 
      become: True
      shell: "{{ m3 }}/conda update -y -q conda"
    - name: set autoupdate
      become: True
      shell: "{{ m3 }}/conda config --set auto_update_conda false"
    - name: set channels
      shell: "{{ m3 }}/conda config --set show_channel_urls True"
    - name: add continiuum.io
      shell: "{{ m3 }}/conda config --add channels https://repo.continuum.io/pkgs/free"
    - name: set conda forge
      shell: "{{ m3 }}/conda config --add channels conda-forge"
    - name: init all
      shell: "{{ m3 }}/conda init --all --verbose"