- name: Install NVM
  block:
    - name: Download NVM
      get_url:
        url: https://github.com/neovim/neovim/releases/download/stable/nvim-macos.tar.gz
        dest: /tmp/nvm.tar.gz
        mode: a+x
    - name: Create NVM config folder
      file:
        path: "{{ home }}/.config/nvim"
        state: directory
        recurse: yes
    - name: Create NVM folder
      file:
        path: "{{ tools }}/nvm"
        state: directory
        recurse: yes
    - name: Extract NVM
      shell: tar zxvf /tmp/nvm.tar.gz --strip-components 1 -C '{{ tools }}/nvm'
    - name: Add to path BASH
      shell: echo export PATH='{{ tools }}/nvm/bin:$PATH' >> '{{ home }}/.profile'
    - name: Add to path FISH
      shell: fish -c "fish_add_path {{ tools }}/nvm/bin"
    - name: Install Packer
      git: 
        repo: https://github.com/wbthomason/packer.nvim
        dest: '{{ home }}/.local/share/nvim/site/pack/packer/opt/packer.nvim'
        depth: 1
    - name: Add init
      get_url:
        url: https://raw.githubusercontent.com/c-jamie/dev-toolchain/master/dotfiles/init.lua
        dest: '{{ home }}/.config/nvim/init.lua'
        mode: '0700'
  tags:
    - nvm-osx
